services:
  ng:

    container_name: myweb
    image: nginx:latest
    networks:
     - lwnet
    ports:
    - 8080:80


  db:

    container_name: mydb1
    image: mysql:latest
    networks:
     - lwnet
    volumes:
    - /data:/var/lib/mysql

    environment:
    - MYSQL_ROOT_PASSWORD=redhat
    - MYSQL_DATABASE=blogdb
    - MYSQL_USER=devang
    - MYSQL_PASSWORD=redhat

networks:
  lwnet: